/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Camara;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import javax.swing.ImageIcon;
import org.opencv.core.Mat;

/**
 *
 * @author mijum
 */
public class JFrameImagen extends javax.swing.JFrame {
    /**
     * Creates new form JFrameImagen
     */
    public JFrameImagen() {
        initComponents();
        //
       // this.jLabelImagen.setIcon(new ImageIcon(imagenOriginal));
        setVisible(true);
    }
    public void nueva(Image imagenOriginal){
        this.setSize(imagenOriginal.getWidth(this), imagenOriginal.getHeight(this));
        
       // imagenOriginal = x.generarImagenEnNegativo(imagenOriginal,true,true,true);
        this.jLabelImagen.setIcon(new ImageIcon(imagenOriginal));
        this.repaint();
    }
 
    public BufferedImage chromakey(BufferedImage imagen){
        Color aux;
        for (int x = 0; x < imagen.getWidth(); x++) {
            for (int y = 0; y < imagen.getHeight(); y++) {
                aux = new Color(imagen.getRGB(x, y));
                
            }
        }
     return imagen;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 300, Short.MAX_VALUE))
        );

        jLabelImagen.getAccessibleContext().setAccessibleName("jLabelImagen");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagen;
    // End of variables declaration//GEN-END:variables
}
